config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all  
    @todo = Todo.new 
  end

  def create
    @todo = Todo.create(description: params[:todo][:description])
    if @todo.valid?
      redirect_to root_path
    else
      render :index
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container p-10 mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/index.html.erb
<h1 class="text-2xl">Todo List</h1>

<%= form_with(model: @todo, class: "my-10") do |form| %>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: "new todo", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-2/4" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<table class="w-3/5 mt-10 border-separate table-auto text-slate-500">
    <thead>
      <tr>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">
          ID
        </th>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">
          Description
        </th>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">
          Action
        </th>
      </tr>
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
            <%= todo.id %>
          </td>
          <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
            <%= todo.description %>
          </td>
          <td class="px-3 py-4 text-sm font-normal text-left text-red-600 underline break-words bg-light">
            <%= button_to "Delete", todo_path(todo), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>